import { db } from "./dbConnection.js";
import express from "express";
import cors from "cors";
const app = express();
app.use(express.json());
app.use(cors());
let PORT = 8080;
app.listen(PORT, `Listening on port ${PORT}`);
app.get("");
app.get("");
app.post("");
app.post("");
